# Generated by Django 5.1.1 on 2024-09-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scheduleAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('appointment_date', models.TimeField()),
                ('appointment_time', models.TimeField()),
                ('doctor_name', models.CharField(max_length=100)),
            ],
        ),
    ]
