# Generated by Django 5.1.1 on 2024-09-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_patient_alter_billing_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('middle_name', models.CharField(default='', max_length=100)),
                ('surname', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default='')),
                ('sex', models.CharField(default='Male', max_length=100)),
                ('marital_status', models.CharField(default='Single', max_length=100)),
                ('phone', models.IntegerField(blank=True, default=0, null=True)),
                ('disability', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
