# Generated by Django 5.1.1 on 2024-09-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_patient_address_patient_age_patient_marital_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
